name: charasgem
description: A versatile calligraphy management and practice application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.3
  sqflite: ^2.3.0
  shared_preferences: ^2.1.1
  provider: ^6.0.5
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  flutter_riverpod: ^2.6.1
  sqflite_common_ffi: ^2.3.5
  intl: ^0.19.0
  file_picker: ^9.0.2  # Make sure this version is compatible
  desktop_drop: ^0.5.0
  uuid: ^4.2.1
  window_manager: ^0.4.3
  archive: ^4.0.4
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  collection: ^1.18.0
  logging: ^1.2.0
  go_router: ^14.8.1
  image: ^4.1.3
  crypto: ^3.0.3
  vector_math: ^2.1.4
  flutter_svg: ^2.0.9  # Add SVG support for rendering outline images
  characters: ^1.3.0  # Add support for Unicode grapheme clusters
  http: ^1.3.0
  flutter_colorpicker: ^1.0.3
  pdf: ^3.10.7
  # printing: ^5.14.2 # Temporarily disabled due to PDFium build issues

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  mockito: ^5.4.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  coverage: ^1.6.3
  flutter_lints: ^2.0.0
  analyzer: ^7.3.0
  benchmark_harness: ^2.2.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf

    # Chinese Fonts
    - family: SourceHanSans
      fonts:
        - asset: assets/fonts/chinese/SourceHanSansCN-Regular.otf
          weight: 400
        - asset: assets/fonts/chinese/SourceHanSansCN-Bold.otf
          weight: 700
        - asset: assets/fonts/chinese/SourceHanSansCN-Light.otf
          weight: 300
        - asset: assets/fonts/chinese/SourceHanSansCN-Medium.otf
          weight: 500
        - asset: assets/fonts/chinese/SourceHanSansCN-Heavy.otf
          weight: 900
        - asset: assets/fonts/chinese/SourceHanSansCN-Normal.otf
          weight: 400
        - asset: assets/fonts/chinese/SourceHanSansCN-ExtraLight.otf
          weight: 200

    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/chinese/NotoSansSC-Regular.ttf
          weight: 400
        - asset: assets/fonts/chinese/NotoSansSC-Bold.ttf
          weight: 700
        - asset: assets/fonts/chinese/NotoSansSC-Light.ttf
          weight: 300
        - asset: assets/fonts/chinese/NotoSansSC-Medium.ttf
          weight: 500
        - asset: assets/fonts/chinese/NotoSansSC-Black.ttf
          weight: 900
        - asset: assets/fonts/chinese/NotoSansSC-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/chinese/NotoSansSC-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/chinese/NotoSansSC-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/chinese/NotoSansSC-Thin.ttf
          weight: 100

    # System Chinese fonts
    - family: SimSun
      fonts:
        - asset: assets/fonts/chinese/simsun.ttc
          weight: 400

    - family: SimHei
      fonts:
        - asset: assets/fonts/chinese/simhei.ttf
          weight: 400

    - family: KaiTi
      fonts:
        - asset: assets/fonts/chinese/simkai.ttf
          weight: 400

    - family: FangSong
      fonts:
        - asset: assets/fonts/chinese/simfang.ttf
          weight: 400

    - family: LiSu
      fonts:
        - asset: assets/fonts/chinese/SIMLI.TTF
          weight: 400

    - family: YouYuan
      fonts:
        - asset: assets/fonts/chinese/SIMYOU.TTF
          weight: 400

    - family: YaHei
      fonts:
        - asset: assets/fonts/chinese/msyh.ttc
          weight: 400
        - asset: assets/fonts/chinese/msyhbd.ttc
          weight: 700
        - asset: assets/fonts/chinese/msyhl.ttc
          weight: 300
