name: demo
description: A calligraphy learning and practicing app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.1
  path: ^1.8.3
  path_provider: ^2.1.2

  # UI
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  go_router: ^13.0.0
  window_manager: ^0.3.7
  file_picker: ^9.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # Image Processing
  image: ^4.1.3

  # Utils
  uuid: ^4.2.2
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: 4.9.0
  intl: 0.19.0
  collection: ^1.18.0
  logger: ^2.0.2+1
  desktop_drop: ^0.5.0
  crypto: ^3.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  
