name: demo
description: A calligraphy character collection app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.6
  flutter_riverpod: ^2.4.9
  cupertino_icons: ^1.0.2
  file_picker: ^9.0.0
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  shared_preferences: ^2.5.2
  window_manager: ^0.4.3  # 添加这一行，使用最新版本
  flutter_gen: ^5.9.0
  sqflite: any
  path: any
  path_provider: ^2.1.5
  uuid: ^4.5.1
  image: ^4.5.2
  sqflite_common_ffi: ^2.3.5
  collection: ^1.19.1
  desktop_drop: ^0.5.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true
  generate: true # 启用代码生成
  
  assets:
    - assets/images/


