name: charasgem
description: A versatile calligraphy management and practice application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.3
  sqflite: ^2.3.0
  shared_preferences: ^2.5.3
  provider: ^6.0.5
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  flutter_riverpod: ^2.6.1
  sqflite_common_ffi: ^2.3.5
  intl: ^0.19.0
  file_picker: ^9.0.2  # Make sure this version is compatible
  desktop_drop: ^0.5.0
  uuid: ^4.2.1
  window_manager: ^0.4.3
  archive: ^4.0.4
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  collection: ^1.18.0
  logging: ^1.2.0
  go_router: ^14.8.1
  image: ^4.1.3
  crypto: ^3.0.3
  vector_math: ^2.1.4
  flutter_svg: ^2.0.9  # Add SVG support for rendering outline images
  characters: ^1.3.0  # Add support for Unicode grapheme clusters
  http: ^1.3.0
  flutter_colorpicker: ^1.0.3
  pdf: ^3.10.7
  # printing: ^5.14.2 # Temporarily disabled due to PDFium build issues
  photo_view: ^0.14.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  mockito: ^5.4.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  coverage: ^1.6.3
  flutter_lints: ^2.0.0
  analyzer: ^7.3.0
  benchmark_harness: ^2.2.2
  msix: ^3.16.9

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf

    # Chinese Fonts (Free for Commercial Use)
    # 使用单一注册方式，依赖FontVariation进行字重控制
    - family: SourceHanSans
      fonts:
        - asset: assets/fonts/chinese/SourceHanSansCN-VF.otf

    - family: SourceHanSerif
      fonts:
        - asset: assets/fonts/chinese/SourceHanSerifCN-VF.otf

    # 测试：使用单独的字体家族名称注册不同字重
    - family: SourceHanSansLight
      fonts:
        - asset: assets/fonts/chinese/SourceHanSansCN-VF.otf
          weight: 300

    - family: SourceHanSansRegular
      fonts:
        - asset: assets/fonts/chinese/SourceHanSansCN-VF.otf
          weight: 400

    - family: SourceHanSansBold
      fonts:
        - asset: assets/fonts/chinese/SourceHanSansCN-VF.otf
          weight: 700
