name: demo
description: A calligraphy character collection app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # 状态管理
  flutter_riverpod: ^2.4.9
  
  # 数据库
  sqlite3: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0
  
  # 工具
  crypto: ^3.0.3
  intl: 0.19.0
  path: any
  path_provider: ^2.1.5
  uuid: ^4.5.1
  
  # UI 相关
  file_picker: ^9.0.0
  image: ^4.5.2
  
  # 窗口管理 (桌面应用)
  window_manager: ^0.4.3
  
  # 本地存储
  shared_preferences: ^2.5.2
  bitsdojo_window: ^0.1.6
  cupertino_icons: ^1.0.2
  flutter_gen: ^5.9.0
  sqflite: any
  sqflite_common_ffi: ^2.3.5
  collection: ^1.19.1
  desktop_drop: ^0.5.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true
  generate: true # 启用代码生成
  
  assets:
    - assets/images/


