name: charasgem
description: A versatile calligraphy management and practice application.
version: 0.0.9+20250830001

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.3
  sqflite: ^2.3.0
  shared_preferences: ^2.5.3
  provider: ^6.0.5
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  flutter_riverpod: ^2.6.1
  sqflite_common_ffi: 2.1.1
  intl: 0.19.0
  file_picker: ^9.0.2  # Make sure this version is compatible
  desktop_drop: ^0.5.0
  uuid: ^4.2.1
  window_manager: ^0.5.1
  archive: ^4.0.4
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  collection: ^1.18.0
  logging: ^1.2.0
  go_router: ^14.8.1
  image: ^4.1.3
  crypto: ^3.0.3
  vector_math: ^2.1.4
  flutter_svg: ^2.0.9  # Add SVG support for rendering outline images
  characters: ^1.3.0  # Add support for Unicode grapheme clusters
  http: ^1.3.0
  flutter_colorpicker: ^1.0.3
  pdf: ^3.10.7
  # printing: ^5.14.2 # Temporarily disabled due to PDFium build issues
  photo_view: ^0.14.0
  mime: ^2.0.0
  xml: ^6.5.0
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  mockito: ^5.4.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  coverage: ^1.6.3
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  
  analyzer: ^7.3.0
  benchmark_harness: ^2.2.2
  msix: ^3.16.9

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: SourceHanSans
      fonts:        
        - asset: assets/fonts/SourceHanSans-VF.otf.ttc

    - family: SourceHanSerif
      fonts:
        - asset: assets/fonts/SourceHanSerif-VF.otf.ttc

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  # 禁用自适应图标以避免裁剪
  adaptive_icon_background: null
  adaptive_icon_foreground: null

# MSIX packaging configuration
msix_config:
  display_name: Char As Gem
  publisher_display_name: 大力出奇迹
  identity_name: C82AF157.CharAsGem
  msix_version: 0.0.9.0
  logo_path: assets/images/logo.png
  architecture: x64
  publisher: CN=53293241-CEA8-41F3-8141-C7ABB9B773E3
  certificate_path: package/windows/msix/CharAsGem.pfx
  certificate_password: password
  store: false
  install_certificate: false
